### ISSUE TITLE
regex with exclusion doesn't work

### ISSUE THREAD

**Issue by amedee** [pbaranchikov/stash-eol-check#4]
I added this regular expression: `\.[p|P][d|D][f|F]`

Then push a commit with the file `cmp_bigRowspanTest06.pdf`.

The hook still complains that this file has the wrong EOL-style.

This is the file in question: https://git.itextsupport.com/projects/I7J/repos/itextcore/browse/layout/src/test/resources/com/itextpdf/layout/TableTest/cmp_bigRowspanTest06.pdf
The `.gitattributes` file in the root of the repository defines `.pdf` files as binary.

**Comment by raspy** [comment]
The root cause is [how the check is done](https://github.com/pbaranchikov/stash-eol-check/blob/174d79006101b37607a1a60777e1c8911f642f51/src/main/java/com/pbaranchikov/stash/checks/EolCheckHook.java#L253): using matches() requires whole string to match (as opposed to find()). Not sure if this is by design, but unless author is willing to change (or at least document it), you may try to change your regexp to: `.*\.[pP][dD][fF]$`

**Comment by pbaranchikov** [comment]
I added a statement to README.md to emphathise the matching strategy.
Thank you a lot.
